apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers: 
      - name: frontend
        image: de.icr.io/cloud-lab-david/frontend:1.1
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports: 
        - containerPort: 8080
        env:
        - name: SEARCH_NLU_ENDPOINT
          valueFrom: 
            secretKeyRef:
              name: frontend-configmap           
              key: SEARCH_NLU_ENDPOINT
        - name: NLU_VERSION
          valueFrom: 
            secretKeyRef:
              name: frontend-secret           
              key: AUTH_USERNAME
        - name: AUTH_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: frontend-secret           
              key: AUTH_PASSWORD
        - name: SESSION_SECRET
          valueFrom: 
            secretKeyRef:
              name: frontend-secret           
              key: SESSION_SECRET      
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10